const sampleproducts = [
    {
        name: "Pre-Workout Powder",
        description: "Boost your energy and focus before hitting the gym",
        image: "image_url_here",
        price: 35,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },
    {
        name: "Gym Duffel Bag",
        description: "Spacious and durable bag for your gym essentials",
        image: "image_url_here",
        price: 40,
        type: "Accessories",
        availability: "15 left",
        review: "Fits everything I need for the gym and more",
    },
    {
        name: "Wrist Wraps (Pair)",
        description: "Provide wrist support for heavy lifts and workouts",
        image: "image_url_here",
        price: 15,
        type: "Accessories",
        availability: "30 left",
        review: "Keeps my wrists stable during intense lifts",
    },
    {
        name: "Running Shoes (Men's/Women's)",
        description: "High-quality running shoes for superior comfort and performance",
        image: "image_url_here",
        price: 80,
        type: "Footwear",
        availability: "Various sizes available",
        review: "Perfect for both casual runs and marathons",
    },
    {
        name: "Compression Socks (Pair)",
        description: "Improve circulation and reduce muscle fatigue during workouts",
        image: "image_url_here",
        price: 20,
        type: "Accessories",
        availability: "25 pairs left",
        review: "A game-changer for long training sessions",
    },
    {
        name: "Protein Powder",
        description: "High-quality protein for muscle recovery and growth",
        image: "image_url_here",
        price: 45,
        type: "supplements",
        availability: "20 left",
        review: "Tastes great and helps me build muscle",
    },
    {
        name: "Creatine Monohydrate Powder",
        description: "Improve strength and endurance for intense workouts",
        image: "image_url_here",
        price: 20,
        type: "supplements",
        availability: "30 left",
        review: "A must for strength training",
    },
    {
        name: "Omega-3 Fish Oil Softgels",
        description: "Support heart health and joint mobility",
        image: "image_url_here",
        price: 15,
        type: "supplements",
        availability: "25 left",
        review: "Keeps me feeling great",
    },
    {
        name: "Vitamin D3 Supplements",
        description: "Boost immune health and bone strength",
        image: "image_url_here",
        price: 10,
        type: "supplements",
        availability: "35 left",
        review: "Essential for overall well-being",
    },
    {
        name: "Amino Acid Blend",
        description: "Support muscle recovery and growth with essential amino acids",
        image: "image_url_here",
        price: 25,
        type: "supplements",
        availability: "15 left",
        review: "Helps me bounce back after tough workouts",
    },
    {
        name: "Stationary Exercise Bike",
        description: "A comfortable, low-impact cardio machine for home workouts",
        image: "image_url_here",
        price: 300,
        type: "Cardio",
        availability: "10 left",
        review: "Great for indoor cycling workouts",
    },
    {
        name: "Kettlebell Set (3 Kettlebells)",
        description: "Versatile kettlebells for strength and endurance training",
        image: "image_url_here",
        price: 50,
        type: "Strength",
        availability: "25 left",
        review: "Perfect for full-body workouts",
    },
    {
        name: "Resistance Bands Kit (11-Piece)",
        description: "Various resistance levels for a wide range of exercises",
        image: "image_url_here",
        price: 30,
        type: "Strength",
        availability: "20 left",
        review: "A complete home gym in one kit",
    },
    {
        name: "Adjustable Dumbbells (Pair)",
        description: "Space-saving, adjustable dumbbells for home workouts",
        image: "image_url_here",
        price: 150,
        type: "Strength",
        availability: "10 left",
        review: "Convenient and easy to use",
    },
    {
        name: "Multi-Purpose Gym Bench",
        description: "Sturdy bench for various strength training exercises",
        image: "image_url_here",
        price: 80,
        type: "Strength",
        availability: "15 left",
        review: "Solid and comfortable for workouts",
    },
    {
        name: "High-Waisted Yoga Pants",
        description: "Stylish and comfortable pants for yoga and athleisure",
        image: "image_url_here",
        price: 35,
        type: "Apparel",
        availability: "30 left",
        review: "My go-to for yoga and relaxation",
    },
    {
        name: "Fitness Tracker Watch",
        description: "Monitor your fitness goals and health metrics",
        image: "image_url_here",
        price: 60,
        type: "Accessories",
        availability: "25 left",
        review: "Tracks everything I need for my workouts",
    },
    {
        name: "Weight Lifting Gloves",
        description: "Protect your hands and improve grip during workouts",
        image: "image_url_here",
        price: 20,
        type: "Accessories",
        availability: "40 left",
        review: "A must for weightlifting sessions",
    },
    {
        name: "Insulated Water Bottle",
        description: "Keep your drinks cold or hot during workouts",
        image: "image_url_here",
        price: 15,
        type: "Accessories",
        availability: "50 left",
        review: "Stylish and practical",
    },
    {
        name: "Extra-Thick Exercise Mat",
        description: "Cushioned mat for yoga, Pilates, and floor exercises",
        image: "image_url_here",
        price: 25,
        type: "Accessories",
        availability: "20 left",
        review: "Comfortable and durable",
    }
];
module.exports={data:sampleproducts};
