const sampleproducts = [

    {
        name: "5kg Dumbell",
        description: "The Flexibell is the latest innovation in Home Fitness, replacing multiple sets of weights. 1 Flexibell is equivalent to 15 different dumbbells. The product has easy-to-use selection dials for adjusting weights.",
        image:"https://cdn-images.cure.fit/www-curefit-com/image/upload/fl_progressive,f_auto,q_auto:eco,w_300,h_400,ar_0.75,c_fill,q_70/dpr_1.5/cultgear-content/cv4GCjuUxcgr5AABQAt1qdCQ",
        price: 750,
        type: "Strength",
        availability: "25 left",
        review: "It lets me hit arms workout like never before",
    },
    {
        name: "Kettlebell",
        description: "Kettlebell exercises often involve several muscle groups at once, making them a highly effective way to give your arms, legs, and abs a great workout in a short amount of time. They can improve both your strength and your cardiovascular fitness.",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6oy1_H8eTzT5xuqoS5LgUEIhU_neT_yAOIraoGbDlWvw9BL3Nr86NVJ10jYWydlHdBAw&usqp=CAU",
        price: 650,
        type: "Strength",
        availability: "15 left",
        review: "Kettlebell has a good grip and a wide range of sizes",
    },

    {
        name: "Barbell",
        description: "No other equipment allows such dramatic improvements in overall strength. Start out using a weight you’re comfortable with, increase the load every week and watch your numbers fly up.",
        image:"https://m.media-amazon.com/images/I/41NZyBUa-lL.jpg",
        price: 850,
        type: "Strength",
        availability: "10 left",
        review: "High quality product and it is very durable",
    },

    {
        name: "jumprope",
        description: "Skipping rope is the best cardio exercise as it increases the heart rate. This will significantly reduce the risk of heart diseases and stroke.",
        image: "https://m.media-amazon.com/images/I/61VqnE79V2L.jpg",
        price: 400,
        type: "Cardio",
        availability: "10 left",
        review: "Great for a quick indoor cardio exercise",
    },
    {
        name: "benches",
        description: "Sturdy,safeand made of leather ",
        image: "https://www.theflexnest.com/cdn/shop/products/Benchfinal_1080x.jpg?v=1639229095",
        price: 450,
        type: "Cardio",
        availability: "17 left",
        review: "Perfect for doing glutes workouts",
    },
    {
        name: "pull up bars",
        description: "Sturdy,safe and high durability ",
        image: "https://m.media-amazon.com/images/I/71N2N1akPwL._AC_UL480_FMwebp_QL65_.jpg",
        price: 500,
        type: "Cardio",
        availability: "17 left",
        review: "Sturdy with a very good grip ",
    },
    {
        name: "core sliders",
        description: "Sturdy,safe and high durability ",
        image: "https://img.fruugo.com/product/5/57/622670575_max.jpg",
        price: 700,
        type: "Cardio",
        availability: "17 left",
        review: "high durability product  ",
    },

    {
        name: "Racks and cages",
        description: "Sturdy,safe and high durability ",
        image: "https://m.media-amazon.com/images/I/51tyWEVlB4L._AC._SR360,460.jpg",
        price: 720,
        type: "Cardio",
        availability: "17 left",
        review: "high durability product  ",
    },
    {
        name: "treadmill",
        description: "Sturdy,safe and high durability ",
        image: "https://v.fastcdn.co/u/db28084b/61790081-0-Smart-run-1.png",
        price: 900,
        type: "Cardio",
        availability: "17 left",
        review: "high durability product  ",
    },
    {
        name: "Assault bike",
        description: "Sturdy,safe and high durability ",
        image: "https://cdn-images.cure.fit/www-curefit-com/image/upload/fl_progressive,f_auto,q_auto:eco,w_500,ar_3:4,c_fill/dpr_2/cultgear-content/gZNKESJuEE5QqZFaCVeZjx8h",
        price: 1000,
        type: "Cardio",
        availability: "17 left",
        review: "high durability product  ",
    },
    {
        name: "Step machine",
        description: "Sturdy,safe and high durability ",
        image: "https://5.imimg.com/data5/SELLER/Default/2023/5/308380990/DQ/NO/ND/60633516/stair-stepper-machine-500x500.png",
        price: 750,
        type: "Cardio",
        availability: "17 left",
        review: "high durability product  ",
    },
    {
        name: "Bigmuscles Protein Powder",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://m.media-amazon.com/images/I/61d6UfDdpsL._SL1200_.jpg",
        price: 835,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },
    {//image
        name: "ATOM Whey Protein Powder",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRmWhosSco8rNBVvr7odGouxepKcedJkT66g_zLe_peCBwCLNEmHpDy_XJWyPnd4zsADkzWnxahMrXgnqocmYJkpSthjQWvSxOspTV3mMX9z3yS6xyPIbO_tWKwx5gfef7hUQaV964v7s8&usqp=CAc",
        price: 1200,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },
    {
        name: "Almond Protein Bar",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://m.media-amazon.com/images/I/618ReTqzmPL._SX679_.jpg",
        price: 250,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },
    {
        name: "Vegan Plant Protein Powder",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://m.media-amazon.com/images/I/71mBvhlzBRL._SY879_.jpg",
        price: 650,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },
    {
        name: "MB Protein Bar",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://m.media-amazon.com/images/I/71YVLXZRUaL._SX679_PIbundle-6,TopRight,0,0_AA679SH20_.jpg",
        price: 1000,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },
    {
        name: "Unibic Snack bar",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://m.media-amazon.com/images/I/51xQDwKC1-L._SX300_SY300_QL70_FMwebp_.jpg",
        price: 135,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },
    {
        name: "Mypro Sport Nutrition",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://m.media-amazon.com/images/I/71irjc91MoL._SY879_.jpg",
        price: 250,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },
    {
        name: "MuscleBlaze Protein Shake",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://m.media-amazon.com/images/I/715KFAQslPL._SX679_.jpg",
        price: 880,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },
    {
        name: "Herbalife Protein Shake",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://m.media-amazon.com/images/I/6128c8J0vSL._SY879_.jpg",
        price: 1050,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },

    {
        name: "Nike mens Air max sport shoes",
        description: "High-quality running shoes for superior comfort and performance",
        image: "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1556130360-vaporfly-4-flyknit-running-shoe-v7G3FB.jpg?crop=0.915xw:0.488xh;0.0449xw,0.322xh",
        price: 800,
        type: "Footwear",
        availability: "Various sizes available",
        review: "Perfect for both casual runs and marathons",
    },
    {
        name: "Nike womans sneakers",
        description: "High-quality running shoes for superior comfort and performance",
        image: "\https://www.tennisnuts.com/images/product/full/WMNS-NIKE-LUNARTEMPO-2-818098_500_C_PREM.jpg",
        price: 870,
        type: "Footwear",
        availability: "Various sizes available",
        review: "Perfect for both casual runs and marathons",
    },
    {
        name: "Nike pegasis Mens running shoes",
        description: "High-quality running shoes for superior comfort and performance",
        image: "https://cdnd.lystit.com/photos/821b-2014/12/02/nike-gray-mens-flex-experience-run-3-wide-running-sneakers-from-finish-line-product-1-25645138-2-977232122-normal.jpeg",
        price: 850,
        type: "Footwear",
        availability: "Various sizes available",
        review: "Perfect for both casual runs and marathons",
    },
    {
        name: "Nike Mens grey jersey",
        description: "Stylish and comfortable pants for yoga and athleisure",
        image: "https://cdnb.lystit.com/photos/2011/09/14/nike-carbon-heather-black-pro-combat-dri-fit-fitted-t-shirt-product-2-1987374-078852542.jpeg'",
        price: 785,
        type: "Apparel",
        availability: "30 left",
        review: "My go-to for yoga and relaxation",
    },
    {
        name: "Nike Womens sweatshirt",
        description: "Stylish and comfortable pants for yoga and athleisure",
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/sweatshirt/p/0/l/s-dq5543-010-nike-original-imagtmufzh6r8uhn.jpeg?q=70",
        price: 835,
        type: "Apparel",
        availability: "30 left",
        review: "My go-to for yoga and relaxation",
    },
    {
        name: "Nike mens Sleveless shirt",
        description: "Stylish and comfortable pants for yoga and athleisure",
        image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f5dc323d-59b6-4779-ae58-81aff0720026/dri-fit-rise-365-running-tank-pr7gXM.png",
        price: 435,
        type: "Apparel",
        availability: "30 left",
        review: "My go-to for yoga and relaxation",
    },
    {
        name: "Nike leggings for women",
        description: "Stylish and comfortable pants for yoga and athleisure",
        image: "'https://i.pinimg.com/originals/b0/81/38/b0813856830cb3fdd659f44ca0a0cfdc.jpg",
        price: 535,
        type: "Apparel",
        availability: "30 left",
        review: "My go-to for yoga and relaxation",
    },
    {
        name: "Nike joggers for men",
        description: "Stylish and comfortable pants for yoga and athleisure",
        image: "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/f2bf2a2d-562a-46dc-9023-885cbc7b53a8/sportswear-club-fleece-mens-joggers-KflRdQ.jpg",
        price: 735,
        type: "Apparel",
        availability: "30 left",
        review: "My go-to for yoga and relaxation",
    },
    {
        name: "Nike joggers for women",
        description: "Stylish and comfortable pants for yoga and athleisure",
        image: "https://img.style-factory.net/nike-ladies-912877-2.jpg",
        price: 635,
        type: "Apparel",
        availability: "30 left",
        review: "My go-to for yoga and relaxation",
    },
    {
        name: "Pre-Workout Powder",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://tse2.mm.bing.net/th?id=OIP.pwur1iAV_fct8-CrJqAHMQHaHa&pid=Api&P=0&h=180",
        price: 335,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },
    {
        name: "Gym Duffel Bag",
        description: "Spacious and durable bag for your gym essentials",
        image: "https://tse4.mm.bing.net/th?id=OIP.0tFX43UgjDIN2bUh2dKS_QHaHa&pid=Api&P=0&h=180",
        price: 400,
        type: "Accessories",
        availability: "15 left",
        review: "Fits everything I need for the gym and more",
    },
    {
        name: "Wrist Wraps (Pair)",
        description: "Provide wrist support for heavy lifts and workouts",
        image: "https://tse1.mm.bing.net/th?id=OIP.12ThVzC_uMp9cS4hzpg_OgHaHa&pid=Api&P=0&h=180",
        price: 115,
        type: "Accessories",
        availability: "30 left",
        review: "Keeps my wrists stable during intense lifts",
    },
    {
        name: "Running Shoes (Men's/Women's)",
        description: "High-quality running shoes for superior comfort and performance",
        image: "https://tse2.mm.bing.net/th?id=OIP.KRbOWMC9SWx__aEuUO1tBgAAAA&pid=Api&P=0&h=180",
        price: 800,
        type: "Footwear",
        availability: "Various sizes available",
        review: "Perfect for both casual runs and marathons",
    },
    {
        name: "Compression Socks (Pair)",
        description: "Improve circulation and reduce muscle fatigue during workouts",
        image: "https://i.insider.com/5b60cbade199f31b008b4851?format=jpeg",
        price: 200,
        type: "Accessories",
        availability: "25 pairs left",
        review: "A game-changer for long training sessions",
    },
    {
        name: "Protein Powder",
        description: "High-quality protein for muscle recovery and growth",
        image: "https://tse3.mm.bing.net/th?id=OIP.0A3lBHUhPCN4q-nmpE4shQHaHa&pid=Api&P=0&h=180",
        price: 245,
        type: "supplements",
        availability: "20 left",
        review: "Tastes great and helps me build muscle",
    },
    {
        name: "Creatine Monohydrate Powder",
        description: "Improve strength and endurance for intense workouts",
        image: "https://i5.walmartimages.com/asr/fa178d77-ed2b-4c15-bb0f-f63a911bcfbc_2.2fa923bd6fa338427f77545c08a73a77.png",
        price: 200,
        type: "supplements",
        availability: "30 left",
        review: "A must for strength training",
    },
    {
        name: "Omega-3 Fish Oil Softgels",
        description: "Support heart health and joint mobility",
        image: "https://i5.walmartimages.com/asr/8a1be5a3-8b5d-4e14-a5d6-4802df2e52a8.8a1599e5f4b2ac8ea90c43c1a57b2046.jpeg",
        price: 150,
        type: "supplements",
        availability: "25 left",
        review: "Keeps me feeling great",
    },
    {
        name: "Vitamin D3 Supplements",
        description: "Boost immune health and bone strength",
        image: "https://i5.walmartimages.com/asr/a8d98710-370e-4bc5-8fd4-04c0ec7adf9d.8c15b50c4e6178d65181f5510e177eca.jpeg",
        price: 100,
        type: "supplements",
        availability: "35 left",
        review: "Essential for overall well-being",
    },
    {
        name: "Amino Acid Blend",
        description: "Support muscle recovery and growth with essential amino acids",
        image: "https://res.cloudinary.com/du8msdgbj/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1534399068/aor9mtxcama2ly2ta3q8.png",
        price: 225,
        type: "supplements",
        availability: "15 left",
        review: "Helps me bounce back after tough workouts",
    },
    {
        name: "Stationary Exercise Bike",
        description: "A comfortable, low-impact cardio machine for home workouts",
        image: "https://i5.walmartimages.com/asr/4894db9c-66ec-4ae6-a734-99fcaf3b076a_1.c40dc02c041478b51f29f9f7dbf87f41.jpeg?odnWidth=1000&odnHeight=1000&odnBg=ffffff",
        price: 300,
        type: "Cardio",
        availability: "10 left",
        review: "Great for indoor cycling workouts",
    },
    {
        name: "Kettlebell Set (3 Kettlebells)",
        description: "Versatile kettlebells for strength and endurance training",
        image: "https://res-5.cloudinary.com/s247/image/upload/c_pad,dpr_1.0,f_auto,q_auto/media/catalog/product/c/o/confidence_pro_3pc_kettlebell_set_main.jpg",
        price: 450,
        type: "Strength",
        availability: "25 left",
        review: "Perfect for full-body workouts",
    },
    {
        name: "Resistance Bands Kit (11-Piece)",
        description: "Various resistance levels for a wide range of exercises",
        image: "https://erp.ener-j.co.uk/web/image/product.image/1842/image?unique=28b5ec9",
        price: 330,
        type: "Strength",
        availability: "20 left",
        review: "A complete home gym in one kit",
    },
    {
        name: "Adjustable Dumbbells (Pair)",
        description: "Space-saving, adjustable dumbbells for home workouts",
        image: "https://i5.walmartimages.com/asr/0d2b0aec-3c0d-49d0-a112-e28d70d36703.509188299c485ce14310c65825a8cbe2.jpeg?odnWidth=1000&odnHeight=1000&odnBg=ffffff",
        price: 1500,
        type: "Strength",
        availability: "10 left",
        review: "Convenient and easy to use",
    },
    {
        name: "Multi-Purpose Gym Bench",
        description: "Sturdy bench for various strength training exercises",
        image: "https://tse4.mm.bing.net/th?id=OIP._IcjW7bkY2I3K-efcO7wcwHaGy&pid=Api&P=0&h=180",
        price: 1800,
        type: "Strength",
        availability: "15 left",
        review: "Solid and comfortable for workouts",
    },
    {
        name: "High-Waisted Yoga Pants",
        description: "Stylish and comfortable pants for yoga and athleisure",
        image: "https://tse4.mm.bing.net/th?id=OIP.2n3IHSVGUgPMJ3h4ORIoywHaJo&pid=Api&P=0&h=180",
        price: 235,
        type: "Apparel",
        availability: "30 left",
        review: "My go-to for yoga and relaxation",
    },
    {
        name: "Fitness Tracker Watch",
        description: "Monitor your fitness goals and health metrics",
        image: "https://i5.walmartimages.com/asr/4b66716f-0d57-4018-8854-7dcfcbd39c3c_1.a7f2f17d2c06f878e2d1279089e7dcdf.jpeg",
        price: 160,
        type: "Accessories",
        availability: "25 left",
        review: "Tracks everything I need for my workouts",
    },
    {
        name: "Weight Lifting Gloves",
        description: "Protect your hands and improve grip during workouts",
        image: "https://tse2.mm.bing.net/th?id=OIP.uOQ3d0IhuyJObiGFkNVR1gHaFm&pid=Api&P=0&h=180",
        price: 290,
        type: "Accessories",
        availability: "40 left",
        review: "A must for weightlifting sessions",
    },
    {
        name: "Insulated Water Bottle",
        description: "Keep your drinks cold or hot during workouts",
        image: "https://images-na.ssl-images-amazon.com/images/I/71yd3F-wi2L._AC_SL1500_.jpg",
        price: 815,
        type: "Accessories",
        availability: "50 left",
        review: "Stylish and practical",
    },
    {
        name: "Extra-Thick Exercise Mat",
        description: "Cushioned mat for yoga, Pilates, and floor exercises",
        image: "https://tse4.mm.bing.net/th?id=OIP.XU831OYXe0MciLOTCThPuQHaEL&pid=Api&P=0&h=180",
        price: 700,
        type: "Accessories",
        availability: "20 left",
        review: "Comfortable and durable",
    }
    {
        name: "Programmer T-shirt",
        description: "A comfortable T-shirt for programming lovers.",
        image: "https://i.pinimg.com/originals/d6/9a/45/d69a453f2f4d53572efa8e8e16e07c11.jpg",
        price: 900,
        type: "Clothing",
        availability: "45 left",
        review: "Comfortable and Good-Looking",
    },
    {
        name: "Naruto Hoodie",
        description: "A cool hoodie for Naruto fans.",
        image: "https://www.hhoodie.com/media/catalog/product/cache/1/image/1000x/9df78eab33525d08d6e5fb8d27136e95/s/h/sh0911216.jpg",
        price: 1700,
        type: "Clothing",
        availability: "12 left",
        review: "Best Hoodie ever!!",
    },
    {
        name: "Skull T-shirt",
        description: "A comfortable T-shirt for Emo Guys.",
        image: "https://i5.walmartimages.com/asr/825007c9-8b9e-49a4-b1a8-76dcf58c718e_1.74a374a2c583a032a43fda95f739ecac.jpeg",
        price: 1200,
        type: "Clothing",
        availability: "29 left",
        review: "cool",
    },
    {
        name: "Simple Fancy T-shirt",
        description: "A comfortable T-shirt for classic men.",
        image: "https://blackberrys.com/cdn/shop/files/Printed_Polo_T_Shirt_In_Maroon_Cancer-ETCC2644R1MA23FL-image1.jpg?v=1694437386",
        price: 2000,
        type: "Clothing",
        availability: "8 left",
        review: "Best Quality ever.",
    },
    {
        name: "Vintage T-shirt",
        description: "The best T-shirt for Aesthitic Lovers.",
        image: "https://blackberrys.com/cdn/shop/files/Printed_Polo_T_Shirt_In_Maroon_Cancer-ETCC2644R1MA23FL-image1.jpg?v=1694437386",
        price: 1500,
        type: "Clothing",
        availability: "21 left",
        review: "This is such a vibe!",
    },
    {
        name: "Active Men Running Shoes - Dark Grey",
        description: "Running shoes for Men",
        image: "https://cdn-images.cure.fit/www-curefit-com/image/upload/fl_progressive,f_auto,q_auto:eco,w_500,ar_3:4,c_fill/dpr_2/cultgear-content/h8iu14v3qLGwK94rBLBdkPGe",
        price: 1900,
        type: "Footwear",
        availability: "3 left",
        review: "Very comfortable and Light.",
    },
    {
        name: "Avant Men's Ultra Light Running and Training Shoes - Grey",
        description: "Sneakers for Men",
        image: "https://cdn-images.cure.fit/www-curefit-com/image/upload/fl_progressive,f_auto,q_auto:eco,w_500,ar_3:4,c_fill/dpr_2/cultgear-content/TbpBqvk7WZYfi9jpUJL92yan",
        price: 1800,
        type: "Footwear",
        availability: "6 left",
        review: "Very comfortable and great grip.",
    },
    {
        name: "X1 Women Training Shoes - Sky Blue",
        description: "Training shoes for Women",
        image: "https://cdn-images.cure.fit/www-curefit-com/image/upload/fl_progressive,f_auto,q_auto:eco,w_500,ar_3:4,c_fill/dpr_2/cultgear-content/gvakbw2aAsDafMWyuMRMXkGF",
        price: 2100,
        type: "Footwear",
        availability: "12 left",
        review: "Perfect shoes for sportswomen.",
    },
    {
        name: "Fresh1947Feet Stone Embellished Laced Up Sneakers - White",
        description: "Best shoes for kids",
        image: "https://cdn.fcglcdn.com/brainbees/images/products/438x531/13689066a.webp",
        price: 2100,
        type: "Footwear",
        availability: "67 left",
        review: "Very soft shoes for Kids.",
    },
    {
        name: "Black Panther: Wakanda Forever Men Low Top Sneakers By Marvel",
        description: "Best shoes for Balck Panther fans.",
        image: "https://th.bing.com/th?id=OPA.2Xpa9GZNJLWi%2bw474C474&w=592&h=550&o=5&dpr=1.3&pid=21.1",
        price: 2300,
        type: "Footwear",
        availability: "28 left",
        review: "Very great shoes!",
    },
    {
        name: "Captain America: The First Avenger Men Low Top Sneakers By Marvel",
        description: "Best shoes for Captain America fans.",
        image: "https://th.bing.com/th?id=OPA.nqGFZ5NV7wBWiQ474C474&w=592&h=550&o=5&dpr=1.3&pid=21.1",
        price: 1970,
        type: "Footwear",
        availability: "12 left",
        review: "The most cool shoes ever!",
    },
    {
        name: "X1 Women Training Shoes - Purple",
        description: "Training shoes for women.",
        image: "https://cdn-images.cure.fit/www-curefit-com/image/upload/fl_progressive,f_auto,q_auto:eco,w_500,ar_3:4,c_fill/dpr_2/cultgear-content/65CqY3JcukmYThiTT4cPdDc9",
        price: 1999,
        type: "Footwear",
        availability: "34 left",
        review: "Very great Shoes for women.",
    },
    {
        name: "Avant Men's Dual Tone Knitted Running shoes- Grey",
        description: "Your Go to running shoes.",
        image: "https://cdn-images.cure.fit/www-curefit-com/image/upload/fl_progressive,f_auto,q_auto:eco,w_500,ar_3:4,c_fill/dpr_2/cultgear-content/hFX4QB3mNuQpGgKymGYRJm4S",
        price: 2199,
        type: "Footwear",
        availability: "67 left",
        review: "Great shoes for running!",
    },
    {
        name: "Hykes Knee cap Compression Support",
        description: "Perfect for a wide range of activities and sports",
        image: "https://m.media-amazon.com/images/I/71AF5VeQrJL._SX679_.jpg",
        price: 609,
        type: "Accessories",
        availability: "15 left",
        review: "Good for fitness. Helping to support knees during exercise.",
    },
    {
        name: "Bodyband Hand Grip Workout Strengthener",
        description: "Adjustable Resistance and Durable Grip",
        image: "https://m.media-amazon.com/images/I/51df0s6DzmL._SX569_.jpg",
        price: 499,
        type: "Accessories",
        availability: "12 left",
        review: "Easy to use and you can adjust of power.",
    },
    {
        name: "PRO365 Home Gym Ab Roller",
        description: "Home Gym Ab Roller/Indoor Ab Wheel for Abs Workout",
        image: "https://m.media-amazon.com/images/I/61aMQ29yayL._SX679_.jpg",
        price: 999,
        type: "Accessories",
        availability: "5 left",
        review: "Grip is good, works perfectly, a value for money product.",
    },
    {
        name: "Boldfit Pull Up Bars For Home Workout",
        description: "Adjustable Length Bar with Anti- slip Pad for sturdy grip",
        image: "https://m.media-amazon.com/images/I/61XAUG2T0gL._SX569_.jpg",
        price: 2999,
        type: "Accessories",
        availability: "10 left",
        review: "It's very sturdy and comfortable. Overall good product to use.",
    },
    {
        name: "Boldfit Resistance Tube with Foam Handles",
        description: "The resistance Tube can be used to exercise all parts of muscles ",
        image: "https://m.media-amazon.com/images/I/614J2Aewg9L._SX569_.jpg",
        price: 899,
        type: "Accessories",
        availability: "7 left",
        review: " Tube is of good quality and overall it is nice product.",
    }
];
module.exports={data:sampleproducts};
